drop table if exists ACTION_LOG;

CREATE TABLE `ACTION_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RELATION_ID` varchar(50) DEFAULT NULL,
  `RESOURCE_ID` varchar(50) NOT NULL,
  `RESOURCE_NAME` varchar(128) DEFAULT NULL,
  `RESOURCE_TYPE` tinyint(3) NOT NULL,
  `ACTION` tinyint(3) NOT NULL DEFAULT '0',
  `USER_NAME` varchar(50) NOT NULL,
  `TENANT_ID` varchar(50) NOT NULL,
  `STATUS` tinyint(3) NOT NULL DEFAULT '0',
  `MESSAGE` varchar(255) NOT NULL,
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `LOGIN_LOG`;

CREATE TABLE `LOGIN_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOGIN_IP` varchar(50) NOT NULL,
  `BROWSER` varchar(255) NOT NULL,
  `LOGIN_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_NAME` varchar(50) NOT NULL,
  `STATUS` tinyint(3) NOT NULL DEFAULT '0',
  `TENANT_ID` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ALARM_LOG`;
CREATE TABLE `ALARM_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TENANT_ID` varchar(50) NOT NULL,
  `TENANT_NAME` varchar(50) NOT NULL,
  `RESOURCE_ID` varchar(50) NOT NULL,
  `RESOURCE_TYPE` tinyint(3) NOT NULL,
  `RESOURCE_NAME` varchar(50) DEFAULT NULL,
  `ALARM_ID` varchar(50) NOT NULL DEFAULT '0',
  `ALARM_NAME` varchar(50) NOT NULL,
  `ALARM_VAL` varchar(255) DEFAULT NULL,
  `STATUS` varchar(50) NOT NULL DEFAULT '0',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop table if exists `DICTIONARY`;

CREATE TABLE `DICTIONARY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(50) DEFAULT NULL,
  `KEY` varchar(50) NOT NULL,
  `CONTEXT` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `DICTIONARY` VALUES (1, 'default', 'SYSTEM_VERSION', 'V2.1.5');
INSERT INTO `DICTIONARY` VALUES (2, 'default', 'SYSTEM_COPYRIGHT', '中电科华云信息技术有限公司');
INSERT INTO `DICTIONARY` VALUES (3, 'default', 'SYSTEM_VIRTUAL_VERSION', '2015.10 V1');
INSERT INTO `DICTIONARY` VALUES (4, 'default', 'SYSTEM_NAME', '电科华云基础设施管理云平台');
INSERT INTO `DICTIONARY` VALUES (5, 'default', 'SYSTEM_LOGO_S_URL', 'assets/images/chinacloud.png');
INSERT INTO `DICTIONARY` VALUES (6, 'default', 'SYSTEM_LOGO_L_URL', 'assets/images/chinacloud.png');
INSERT INTO `DICTIONARY` VALUES (7, 'default', 'SYSTEM_FAVICON_URL', 'assets/images/favicon.ico');
